apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-eks
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.3.1
    helm:
      values: |
        pushgateway:
          enabled: false
  destination:
    server: https://203E6F1C1476D9586B62C2849A7BDF62.yl4.eu-west-3.eks.amazonaws.com
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
